services:
  rasp:
    image: ${rasp_image}:${wrf}_${region}
    build: .
    volumes:
      - ../results/OUT:/root/rasp/${region}/OUT
      - ../results/LOG:/root/rasp/${region}/LOG
    environment:
      - START_DAY=${START_DAY:-0}
      - OFFSET_HOUR=${OFFSET_HOUR:-0}
