services:
  base:
    image: ${BASE_IMAGE}
    build:
      context: ./base
      dockerfile: Dockerfile
  wrf_build:
    image: ${WRF_IMAGE}:${WRF_VERSION}-${WRF_MARCH_BUILD}
    build:
      context: ./wrf
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${BASE_IMAGE}
        WRF_VERSION: ${WRF_VERSION}
        WPS_VERSION: ${WPS_VERSION}
        WRF_MARCH: ${WRF_MARCH_BUILD}
  wrf_prod:
    image: ${WRF_IMAGE}:${WRF_VERSION}-${WRF_MARCH_PROD}
    build:
      context: ./wrf
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${BASE_IMAGE}
        WRF_VERSION: ${WRF_VERSION}
        WPS_VERSION: ${WPS_VERSION}
        WRF_MARCH: ${WRF_MARCH_PROD}
  rasp:
    image: ${RASP_IMAGE}:WRF${WRF_VERSION}_${REGION}
    build:
      context: ./rasp
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${BASE_IMAGE}
        WRF_IMAGE: ${WRF_IMAGE}
        WRF_VERSION: ${WRF_VERSION}
        WRF_MARCH_BUILD: ${WRF_MARCH_BUILD}
        WRF_MARCH_PROD: ${WRF_MARCH_PROD}
        REGION: ${REGION}
    volumes:
      - ../results/OUT:/root/rasp/${REGION}/OUT
      - ../results/LOG:/root/rasp/${REGION}/LOG
    environment:
      - START_DAY=${START_DAY:-0}
      - OFFSET_HOUR=${OFFSET_HOUR:-0}
